### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by xudong19** [TUMFTM/CameraRadarFusionNet#1]
Hi,

I tried different ways (using conda and docker) to install your module but all failed. Could you please double check the setup.py really works to get the module to run? Really appreciate it!

**Comment by fnobis** [comment]
Thanks for the feedback. 
The docker image is now updated.There were indeed some path issues due to the change to the public repository.

For the usage outside of docker, we recommend the usage of a virtual environment. The repository is not tested with conda.

**Comment by xudong19** [comment]
Thanks so much for the prompt reply and fix. I will try it later. 

You said you recommend the usage of a virtual environment, do you mean using virtualenv to manage the environment? Cause when I said I tried conda before, I I also used the virtual environment, only managed by conda, but it did not work. Could you please elaborate more specifically?

**Comment by fnobis** [comment]
We do not test the environment in conda nor under windows. For general advise with conda refer to their documentation.
