### ISSUE TITLE
ModuleNotFoundError: No module named 'crfnet'

### ISSUE THREAD

**Issue by Dhanush0692** [TUMFTM/CameraRadarFusionNet#16]
Hi,
I followed the commands as given in the git repository of  TUMFTM /CameraRadarFusionNet.
**sudo apt install graphviz**
**pip install -e .** and 
**python setup.py build_ext --inplace**

But when i try executing **fusion_projection_lines.py** it gives me **ModuleNotFoundError** which is **No module named 'crfnet'**
Although it says crfnet is installed. Attached screenshot for the same. Can you please let me know where am i going wrong.

Thanks,

**Comment by programmeeer** [comment]
how did you solved?

**Comment by BoxunFeng** [comment]
how did you sloved?
