### ISSUE TITLE
Index error: List of Index out of range

### ISSUE THREAD

**Issue by MI-Hussain** [TUMFTM/CameraRadarFusionNet#2]
![error](https://user-images.githubusercontent.com/44750142/73834161-8ee14b80-484e-11ea-8cb9-9b7e5c3bbdf9.png)
Help is requested please.

**Comment by fnobis** [comment]
There seems to be a problem with the loading of the nuScenes dataset in your case. Verify that you have downloaded the dataset and set the config accordingly. For further information, refer to the nuScenes documentation directly.

**Comment by MI-Hussain** [comment]
Sorry to disturb you again. Actually I am new in that. 

I downloaded mini (Subset of trainval, 10 scenes, used to explore the data without downloading the whole dataset.)

I think the dataset is loading properly (as shown in picture). But the error is coming in create_generators.


![new](https://user-images.githubusercontent.com/44750142/74336273-4a6f2600-4de1-11ea-96c5-93a68620b29f.gif)

**Comment by mgeisslinger** [comment]
As you said, you are using nuscenes-mini. According to the loading message you are loading nuscnes-trainval.
If you want to try on nuscenes-mini, please try changing the "data_set" parameter in the config from nuscenes to nuscenes-mini.

**Comment by MI-Hussain** [comment]
Yeah you were right. the problem was due to loading the dataset. But it stuck in training after 2 epoch.
