### ISSUE TITLE
h5py import error

### ISSUE THREAD

**Issue by fractral** [TUMFTM/CameraRadarFusionNet#22]
The version `h5py==2.7.1` leads to an import error on Ubuntu 16.04  Python 3.7. 

```python -c "import h5py"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/<username>/programs/anaconda3/envs/python3.7/lib/python3.7/site-packages/h5py/__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/_conv.pyx", line 1, in init h5py._conv
  File "h5py/h5r.pyx", line 1, in init h5py.h5r
  File "h5py/_objects.pyx", line 1, in init h5py._objects
ImportError: /home/<username>/programs/anaconda3/envs/python3.7/lib/python3.7/site-packages/h5py/defs.cpython-37m-x86_64-linux-gnu.so: undefined symbol: H5Ovisit_by_name```


Could it be that Python 3.6. is required?

**Comment by Fellfalla** [comment]
> The version `h5py==2.7.1` leads to an import error on Ubuntu 16.04 Python 3.7.
> 
> ```python
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/<username>/programs/anaconda3/envs/python3.7/lib/python3.7/site-packages/h5py/__init__.py", line 36, in <module>
>     from ._conv import register_converters as _register_converters
>   File "h5py/_conv.pyx", line 1, in init h5py._conv
>   File "h5py/h5r.pyx", line 1, in init h5py.h5r
>   File "h5py/_objects.pyx", line 1, in init h5py._objects
> ImportError: /home/<username>/programs/anaconda3/envs/python3.7/lib/python3.7/site-packages/h5py/defs.cpython-37m-x86_64-linux-gnu.so: undefined symbol: H5Ovisit_by_name```
> 
> 
> Could it be that Python 3.6. is required?
> ```

As described in the requirements section of the readme, we've tested the repository with python 3.5. However, I don't know if thats the reason for your error. You might try a different version of h5py. As far as I remember, we ran into issues with h5py as well and thus had to specify this version.

**Comment by fractral** [comment]
Thanks. I will try it.
