### ISSUE TITLE
No module named 'crfnet.utils.compute_overlap' | for train _crfnet.py

### ISSUE THREAD

**Issue by RRK13** [TUMFTM/CameraRadarFusionNet#6]
Error while executing the  "python train_crfnet.py --config configs/crf_net.cfg"

`
File "../crfnet/model/layers/_misc.py", line 24, in <module>
    from crfnet.utils.anchor import generate_anchors
  File "../crfnet/utils/anchor.py", line 9, in <module>
    from .anchor_calc import compute_overlap
  File "../crfnet/utils/anchor_calc.py", line 13, in <module>
    **_from ..utils.compute_overlap import compute_overlap
ModuleNotFoundError: No module named 'crfnet.utils.compute_overlap'_**
`

Same issue with "`python test_crfnet.py --model saved_models/crf_net.h5 --config configs/crf_net.cfg --st 0.5`"

**Comment by mgeisslinger** [comment]
Did you run the following command for installation?

`python setup.py build_ext --inplace`

**Comment by RRK13** [comment]
Thank you
